[package]
name = "dxc-types"
edition.workspace = true
rust-version.workspace = true
version.workspace = true
authors.workspace = true
description = "DEPRECATED: Use dxc instead."
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords = []

[dependencies]
dioxus = { workspace = true }
serde = { workspace = true }
strum = { workspace = true }
