[source.crates-io]
# replace-with = "aliyun"
registry = "https://github.com/rust-lang/crates.io-index/"

[registries]
aliyun = { index = "https://mirrors.aliyun.com/crates.io-index/" }

[build]
target-dev = "target"
