[package]
name = "dxc-utils"
edition.workspace = true
rust-version.workspace = true
version.workspace = true
authors.workspace = true
description = "DEPRECATED: Use dxc instead."
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords = []

[dependencies]
